// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADdEHQtKNa6k68sFD261uYnHZcf75A4t4',
    appId: '1:440349205768:web:6749ba2a11267fd0d5f8bd',
    messagingSenderId: '440349205768',
    projectId: 'stockedge-new',
    authDomain: 'stockedge-new.firebaseapp.com',
    storageBucket: 'stockedge-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeMPD8rTjsZikrdwA3HkV1pKJbALMpieM',
    appId: '1:440349205768:android:d165596123d29c81d5f8bd',
    messagingSenderId: '440349205768',
    projectId: 'stockedge-new',
    storageBucket: 'stockedge-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPVTGoBZrGNXhd18oPIU06fx_MZtuUqVA',
    appId: '1:440349205768:ios:53a37d3d3e97fa67d5f8bd',
    messagingSenderId: '440349205768',
    projectId: 'stockedge-new',
    storageBucket: 'stockedge-new.appspot.com',
    iosClientId: '440349205768-ee4t8k3ug2midn9jq6ji42rg6cqg53lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockedgeNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPVTGoBZrGNXhd18oPIU06fx_MZtuUqVA',
    appId: '1:440349205768:ios:53a37d3d3e97fa67d5f8bd',
    messagingSenderId: '440349205768',
    projectId: 'stockedge-new',
    storageBucket: 'stockedge-new.appspot.com',
    iosClientId: '440349205768-ee4t8k3ug2midn9jq6ji42rg6cqg53lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockedgeNew',
  );
}
